---
- name: Install Docker
  ansible.builtin.yum:
    name: docker
    state: present

- name: Start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Deploy private Docker registry container
  ansible.builtin.docker_container:
    name: registry
    image: registry:2
    ports:
      - "5000:5000"
    state: started

