---
- name: Copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: /home/ubuntu/docker-compose.yml
    mode: '0644'

- name: Deploy Docker container
  shell: docker-compose up -d
  args:
    chdir: /home/ubuntu

