---
- name: Install dependencies (Python3, pip)
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: Install Django
  ansible.builtin.pip:
    name: django

- name: Clone your app repository
  ansible.builtin.git:
    repo: 'https://github.com/yourusername/your-django-app.git'
    dest: /opt/myapp

- name: Run Django server
  ansible.builtin.shell: |
    python3 manage.py runserver 0.0.0.0:8000
  args:
    chdir: /opt/myapp
  async: 600
  poll: 0

